"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["main.py"]
APP_NAME = "应用程序"
APP_VERSION = "0.0.1"
DATA_FILES = ["lib", "data", "components", "pages"]
OPTIONS = {
    "argv_emulation": True,
    "iconfile": "data/image/128.icns",
    "plist": {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleGetInfoString": "doudoudzj",
        "CFBundleIdentifier": "com.crogram.osx.application",
        "CFBundleVersion": APP_VERSION,
        "CFBundleShortVersionString": APP_VERSION,
        "NSHumanReadableCopyright": "Copyright © 2018, Crogram, Inc., All Rights Reserved",
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
